### ISSUE TITLE
Change the repository for cargo-ebuild on crates.io

### ISSUE THREAD

**Issue by leonardohn** [gentoo/cargo-ebuild#14]
Currently, the crate for cargo-ebuild is pointing to `cardoe/cargo-ebuild`. We need @cardoe to update the crate so it points to the updated repository.

**Comment by gyakovlev** [comment]
I've contacted @cardoe to sort this out already. on it, thanks =)

**Comment by vincentdephily** [comment]
In the meantime (it's been a year with no change ?), maybe fix the installation instruction to `cargo install cargo-ebuild --git https://github.com/gentoo/cargo-ebuild` and/or `emerge cargo-ebuild` ?

**Comment by gyakovlev** [comment]
This is finally done.
https://crates.io/crates/cargo-ebuild/versions
