### ISSUE TITLE
Publish recent versions to crates.io 

### ISSUE THREAD

**Issue by vincentdephily** [gentoo/cargo-ebuild#24]
Why does is the [cargo-ebuild published on crates.io](https://crates.io/crates/cargo-ebuild) still stuck at version 0.3.1 ? I've just discovered by luck that development hadn't stopped 2 years ago. The readme still says to install using `cargo install cargo-ebuild`.

**Comment by gyakovlev** [comment]
@vincentdephily original cargo-ebuild author retired from gentoo, it's now maintained by me and several very good contributors.

we don't have crates.io access, we need @cardoe to somehow transfer it to me or take it down so we can replace it, idk how it works.

original issue is here: https://github.com/gentoo/cargo-ebuild/issues/14
let's use it for future discussion.
