### ISSUE TITLE
Handle missing whitespace around parentheses in license strings

### ISSUE THREAD

**Issue by mgorny** [gentoo/cargo-ebuild#27]
Noticed on https://files.pythonhosted.org/packages/13/dd/a9608b7aebe5d2dc0c98a4b2090a6b815628efa46cc1c046b89d8cd25f4c/cryptography-38.0.3.tar.gz

```
WARNING: unknown license "(MIT", please correct manually
WARNING: unknown license "Apache-2.0)", please correct manually
WARNING: unknown license "Unicode-DFS-2016", please correct manually
Wrote: cryptography-rust-0.1.0.ebuild
```

I'm guessing that one of the crates doesn't follow SPDX strictly and didn't add whitespace around parentheses in the license string. That said, it'd be nice if cargo-ebuild actually said which crate caused that.

**Comment by leonardohn** [comment]
I just sent a pull request with a fix for that. Please let me know if it works.
